// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Qel.Ef.Contexts.Main;

#nullable disable

namespace Qel.Ef.DesignTimeUtils.Migrations.Main
{
    [DbContext(typeof(DbContextMain))]
    [Migration("20240921165357_Fill")]
    partial class Fill
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Qel.Ef.Models.Passport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)");

                    b.HasKey("Id");

                    b.ToTable("Passports", null, t =>
                        {
                            t.HasComment("Паспортные данные клиента");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Number = "123456",
                            Serie = "0311"
                        },
                        new
                        {
                            Id = 2L,
                            Number = "213455",
                            Serie = "2228"
                        });
                });

            modelBuilder.Entity("Qel.Ef.Models.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<long>("PassportId")
                        .HasColumnType("bigint");

                    b.HasKey("Id");

                    b.HasIndex("PassportId");

                    b.ToTable("Persons", null, t =>
                        {
                            t.HasComment("Физические лица, отправляющие заявки в банк");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Birthdate = new DateTime(2024, 9, 21, 16, 53, 57, 62, DateTimeKind.Utc).AddTicks(6161),
                            FirstName = "Иван",
                            LastName = "Иванов",
                            PassportId = 1L
                        },
                        new
                        {
                            Id = 2L,
                            Birthdate = new DateTime(9999, 12, 31, 23, 59, 59, 999, DateTimeKind.Unspecified).AddTicks(9999),
                            FirstName = "Владимир",
                            LastName = "Горбатый",
                            PassportId = 2L
                        });
                });

            modelBuilder.Entity("Qel.Ef.Models.Request", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Period")
                        .HasMaxLength(128)
                        .HasColumnType("integer");

                    b.Property<int>("Summa")
                        .HasMaxLength(128)
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Requests", null, t =>
                        {
                            t.HasComment("Заявка в банк");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Period = 12,
                            Summa = 100000
                        },
                        new
                        {
                            Id = 2L,
                            Period = 36,
                            Summa = 1230900
                        });
                });

            modelBuilder.Entity("Qel.Ef.Models.Person", b =>
                {
                    b.HasOne("Qel.Ef.Models.Passport", "Passport")
                        .WithMany()
                        .HasForeignKey("PassportId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passport");
                });
#pragma warning restore 612, 618
        }
    }
}
