// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Qel.Ef.Contexts.Main;

#nullable disable

namespace Qel.Ef.DesignTimeUtils.Migrations.Main
{
    [DbContext(typeof(DbContextMain))]
    partial class DbContextMainModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Qel.Ef.Models.Passport", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Number")
                        .HasMaxLength(16)
                        .HasColumnType("integer");

                    b.Property<int>("Serie")
                        .HasMaxLength(8)
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Passport", null, t =>
                        {
                            t.HasComment("Паспортные данные клиента");
                        });
                });

            modelBuilder.Entity("Qel.Ef.Models.Person", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("Birthdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.HasKey("Id");

                    b.ToTable("Persons", null, t =>
                        {
                            t.HasComment("Физические лица, отправляющие заявки в банк");
                        });
                });

            modelBuilder.Entity("Qel.Ef.Models.Request", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("Id"));

                    b.Property<int>("Period")
                        .HasMaxLength(128)
                        .HasColumnType("integer");

                    b.Property<int>("Summa")
                        .HasMaxLength(128)
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Requests", null, t =>
                        {
                            t.HasComment("Заявка в банк");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
