name: myef
networks:
  db_postgres_net:
services:
  dbPostgres:
    image: postgres:alpine3.20
    env_file:
      - .env
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      interval: 30s
      timeout: 30s
      retries: 10
    ports:
      - 32942:5432